version: "3"
services:
  emily-yolov5-client-xfjp1q:
    image: emily-yolov5-client-xfjp1q
    container_name: emily-yolov5-client-xfjp1q
    networks:
      - emily-yolov5-client-xfjp1q-network
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
    ports:
      - ${NOTEBOOK_PORT}
    runtime: ${RUNTIME}
    environment:
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES}
      - NVIDIA_DRIVER_CAPABILITIES=${NVIDIA_DRIVER_CAPABILITIES}
    ipc: ${IPC}
networks:
  emily-yolov5-client-xfjp1q-network:
    name: emily-yolov5-client-xfjp1q-network
    driver: bridge
